# Copyright 2020 (c) Ayane Satomi
# Published under CC0-Universal.
#
#
# Keep in mind this configuration is domain-specific, some things may not work in your end.
apiVersion: v1
kind: ConfigMap
metadata:
  name: fabric-suzuhara-config
  annotations:
    mc.suzuhara.moe/deployment: minecraft
data:    
  server.properties: |
    generator-settings=
    use-native-transport=true
    op-permission-level=4
    allow-nether=true
    level-name=suzuhara
    enable-query=false
    allow-flight=false
    prevent-proxy-connections=false
    server-port=25565
    max-world-size=29999984
    level-type=DEFAULT
    enable-rcon=false
    level-seed=konlulu
    force-gamemode=false
    server-ip=
    network-compression-threshold=256
    max-build-height=256
    spawn-npcs=true
    white-list=false
    spawn-animals=true
    hardcore=false
    snooper-enabled=true
    resource-pack-sha1=
    online-mode=true
    resource-pack=
    pvp=false
    difficulty=0
    enable-command-block=false
    gamemode=0
    player-idle-timeout=0
    max-players=20
    spawn-monsters=true
    generate-structures=true
    view-distance=10
    motd=Welcome to the Suzuhara Experimental Minecraft Server. Keep in mind QoS is not guranteed as this is an experiment. If you want to support us, consider being donator at https://ko-fi.com/capuccino